language: node_js
node_js:
  - "0.12"
script:
  - "npm run lint"
  - "npm run build"
  - "./node_modules/.bin/karma start --browsers Firefox --single-run"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
